server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-catalog
  zipkin:
    base: http://localhost:9411
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      username: usrcatalog
      password: pwdcatalog
      database: catalog
      port: 27018
      host: localhost

queue:
  movie:
    name: MovieQueue

message: hello Catalog up

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true