server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  data:
    mongodb:
      database: tp_final
      port: 27017
      host: localhost

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  rabbitmq:
    usename: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka

